### ISSUE TITLE
Variables leaking into global namespace from AMD module

### ISSUE THREAD

**Issue by p3k** [directwebremoting/dwr#4]
I found these two variables defined in `engine.js` becoming global variables:

1. dwr
2. httpMethod

`dwr` seems to be globally assigned in [line 620ff.](https://github.com/directwebremoting/dwr/blob/master/core/impl/main/java/org/directwebremoting/engine.js#L625) by purpose(?) although it is not quite clear to me, why.

However, `httpMethod` is IMHO missing its variable declaration and thus, is erroneously interpreted as global variable in [line 1669](https://github.com/directwebremoting/dwr/blob/master/core/impl/main/java/org/directwebremoting/engine.js#L1669).

**Comment by mikewse** [comment]
**httpMethod**
Good catch, thanks for letting us know! Fix arriving shortly.

**dwr global**
Yes, as you suspect this is intentional. Explaining the reason needs a fairly deep technical understanding of the effects of different DWR features, but in short this is how it goes:

- the AMD loader allows several independent DWR instances to be loaded in the same page ("multi-version support")
- when using script tag remoting the responses from the server need to be executed in the global scope
- therefore each DWR instance is assigned an instanceId and registered in the global array dwr._ so remote responses may look up the correct instance to execute in

Note that the instance array _[] is the only child of the global dwr variable in AMD environments. The full DWR API is exposed under the respective instance.

We would of course like to avoid any globals at all, but removing this dependency is non-trivial as that would require the server to be aware of what kind of Javascript module system configuration is used in the client, to be able to look up the correct DWR instance.

**Comment by p3k** [comment]
thanks for reacting so quickly. 
😺 

just one follow-up question regarding the global dwr variable: if i knew for sure i only used one instance of dwr would maybe a configuration option make sense? this, way i could deliberately disable the global definition. 

of course, only given i actually *can* be sure about the amount of instances used, i.e. if this is not beyond my control…?

**Comment by mikewse** [comment]
A global would still be required for script tag remoting to work (to find the one DWR instance).

Honestly, we haven't regarded the dwr global as a big enough problem to take any actions against it in the current DWR 3.x codebase. And there are already too many settings. The next time we do a major refactoring of the DWR protocol and the client-side code we will for sure fix it though, but there are no plans at the moment.

**Comment by p3k** [comment]
ok, that makes sense. thanks for the clarification!
